### ISSUE TITLE
Please consider update v2 and v2.0 tag to the latest v2.x/v2.0.x release 

### ISSUE THREAD

**Issue by RadxaYuntian** [josStorer/get-current-time#15]
It is recommended to [**Move the major version tag** (such as v1, v2) to point to the Git ref of the current release](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management) per official documentation.

I usually use major version tag for GitHub Actions in my workflow, and I was surprised that this action is still giving me Node 12 deprecated warning. The old action was unmaintained which is why I'm looking for alternative.

**Comment by josStorer** [comment]
You are right, I did not notice that, now I have updated v1, v1.0, v2, v2.0, see more in [tags](https://github.com/josStorer/get-current-time/tags)
