### ISSUE TITLE
[FR] Date Range UTC adjustment (for Daylight Savings or anything similar)

### ISSUE THREAD

**Issue by God-damnit-all** [josStorer/get-current-time#19]
An option for adjusting the UTC offset for Daylight Savings would be appreciated.

Since Daylight Savings varies by region, it could accept from & to inputs on when it should be active, as well as what to adjust the UTC offset by.

**Comment by josStorer** [comment]
good idea, I'll look at it when I'm free in the next few days

**Comment by josStorer** [comment]
I eventually decided to add a `timezone` input field, which may be more user-friendly. Check [Readme](https://github.com/josStorer/get-current-time/blob/master/README.md) and [Release](https://github.com/josStorer/get-current-time/releases) for more details
