### ISSUE TITLE
Was this originally the aciton created by 1466587594

### ISSUE THREAD

**Issue by JoseThen** [josStorer/get-current-time#2]
All searches for `uses: 1466587594/get-current-time@v2` keep leading me here. Was the repository moved or name changed?

**Comment by josStorer** [comment]
Yes, I changed my username to `josStorer`, because the original name `1466587594` is too long and hard to remember.

Also, I created an alt account with the original name, without any repositories, so I could keep some redirects.

**Comment by pzhlkj6612** [comment]
> I created an alt account with the original name... so I could keep some redirects.

Nice work bro!

**Comment by JoseThen** [comment]
Yea this is great thank you! Also I feel you on that `int as a name` 😆
