### ISSUE TITLE
Error: Unable to resolve actions. Repository not found : 1466587594/get-current-time.

### ISSUE THREAD

**Issue by santroshg** [josStorer/get-current-time#3]
Getting below error
Error: Unable to resolve actions. Repository not found : 1466587594/get-current-time.
with below code 
    steps:
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+08:00"
      - name: Use current time
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
          R_TIME: "${{ steps.current-time.outputs.readableTime }}"
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
          YEAR: "${{ steps.current-time.outputs.year }}"
          DAY: "${{ steps.current-time.outputs.day }}"
        run: echo checked all tests $TIME $R_TIME $F_TIME $YEAR $DAY

**Comment by pzhlkj6612** [comment]
Hi! Please see #2 .

**Comment by josStorer** [comment]
I took a test [here](https://github.com/josStorer/get-current-time/runs/4896874974?check_suite_focus=true) for the redirect, and [here](https://github.com/josStorer/get-current-time/blob/test/.github/workflows/main.yml) is the workflow file. I didn't find any errors.

**Comment by josStorer** [comment]
May I ask what environment your repository work in, I used a different account and created a new repo, with this action. Everything works fine.

**Comment by josStorer** [comment]
Long time no response.
